### ISSUE TITLE
simpleColorChooser box is not getting displayed

### ISSUE THREAD

**Issue by dsamit** [recurser/jquery-simple-color#26]
I am trying to use 'jquery-simple-color'.

The issue is when i am clicking on 'simpleColorDisplay' div for selecting color the 'simpleColorChooser' box is not getting displayed.
What should be done in order to get visible the color chooser box.

Thanks,
Amit

**Comment by recurser** [comment]
@dsamit apologies for the huge delay here. I'm going to close this since it has been so long, and there have been no other reports of this issue.

If you're still having problems, feel free to re-open this. If could you provide a sample HTML page demonstrating the issue it would be even better.
