### ISSUE TITLE
Undefined `options` in `$.fn.setColor`

### ISSUE THREAD

**Issue by al42and** [recurser/jquery-simple-color#31]
Hello!

Thank you for this nice library! 

It seems that, in the course of resolving Issue #29, an error was introducing during [the refactoring](https://github.com/recurser/jquery-simple-color/commit/5cac4c9d5ddf2946324acf0bb8a019486f0b9b69#diff-ef970c4d971fd86b4aad734653f5b3a0R378):

On [this line](https://github.com/recurser/jquery-simple-color/blob/develop/src/jquery.simple-color.js#L378), the `options` are currently undefined.

I'm not very familiar with JS, but I believe the call should be something along the lines of `setColor(displayBox, color, {'displayColorCode: displayBox.data('displayColorCode'));`.

**Comment by recurser** [comment]
Thanks for the heads-up @al42and! 🙇 Fixed in [v1.2.3](https://github.com/recurser/jquery-simple-color/releases/tag/v1.2.3)
